# DomainBed + ResNet 实验配置文件

# 数据集配置
dataset:
  name: "TerraIncognita"  # ColoredMNIST, TerraIncognita, PACS, OfficeHome, VLCS
  data_dir: "./DomainBed/domainbed/data/"
  test_env: 0
  
# 模型配置
model:
  type: "resnet34"  # resnet18, resnet34, resnet50
  pretrained: true
  input_channels: null  # null表示自动从数据集获取
  dropout_rate: 0.4 # 统一关闭Dropout

# 训练配置
training:
  epochs: 100
  batch_size: 128 # 修改为 128
  learning_rate: 0.1 # 修改为 0.1
  optimizer_type: "SGD"  # 指定优化器类型
  momentum: 0.9          # SGD的动量参数
  weight_decay: 0.0001
  step_size: 50 # 学习率衰减步长
  gamma: 0.1
  mixed_precision: true  # 启用混合精度训练 (自动混合精度 AMP)
  
# 实验配置
experiment:
  name: "resnet_domain_experiment"
  device: "auto"  # auto, cuda, cpu
  num_workers: 4
  pin_memory: true
  seed: 42
  
# 输出配置
output:
  save_model: true
  model_path: "./models/"
  results_path: "./results/"
  log_path: "./logs/"
  plot_results: true
  
# 实验批次配置 (用于批量实验)
batch_experiments:
  enabled: true
  datasets: ["ColoredMNIST"]
  test_envs: [0, 1]
  learning_rates: [0.0001, 0.0005]
  batch_sizes: [16, 32]
